#!/bin/bash

# Gtkdialog3 executes action commands using the user's $SHELL,
# so bash exported functions (export -f) work directly in actions.

GTKDIALOG=gtkdialog3

print_this() {
	echo "print: $1"
}; export -f print_this

export MAIN_DIALOG='
<window title="Bash Event Driven">
	<vbox>
		<text>
			<label>"Exported bash function demo (export -f)"</label>
		</text>
		<button>
			<label>Call print_this()</label>
			<action>print_this button</action>
		</button>
		<button>
			<label>Exit</label>
		</button>
	</vbox>
</window>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
