#!/bin/bash

# Gtkdialog3 executes action commands via system(), which uses /bin/sh.
# On many systems /bin/sh is dash, which does not support bash's
# "export -f" mechanism. This example requires bash as /bin/sh, or
# the script must be run with bash explicitly.

GTKDIALOG=gtkdialog3

print_this() {
	echo "print: $1"
}; export -f print_this

export MAIN_DIALOG='
<window>
	<vbox>
		<button>
			<label>function</label>
			<action>bash -c "print_this button"</action>
		</button>
		<button>
			<label>Exit</label>
		</button>
	</vbox>
</window>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
