#!/bin/sh

GTKDIALOG=gtkdialog3

IMAGEFILE="`find /usr/share/pixmaps -maxdepth 1 -type f | head -1`"

MAIN_DIALOG='
<window>
	<vbox>
		<hbox>
			<button>
				<label>Label</label>
				<action>echo You pressed the button with the label.</action>
			</button>
			<button>
				<width>16</width>
				<input type="file">'"$IMAGEFILE"'</input>
				<action>echo You pressed the button with the pixmap.</action>
			</button>
		</hbox>
		<hbox>
			<button stock="yes">
				<action>echo You pressed the Yes button.</action>
			</button>
			<button stock="no">
				<action>echo You pressed the No button.</action>
			</button>
		</hbox>
		<hbox>
			<button stock="ok">
				<action>echo You pressed the OK button.</action>
			</button>
			<button stock="cancel">
				<action>echo You pressed the Cancel button.</action>
			</button>
			<button stock="help">
				<action>echo You pressed the Help button.</action>
			</button>
		</hbox>
		<hbox>
			<button stock="ok"/>
			<button stock="cancel"/>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
