#!/bin/sh

GTKDIALOG=gtkdialog3

MAIN_DIALOG='
<window>
	<vbox>
		<hbox>
			<button>
				<input type="icon">xterm</input>
				<action>echo xterm</action>
			</button>
			<button>
				<input type="icon">xarchive</input>
				<action>echo xarchive</action>
			</button>
			<button>
				<input type="icon">urxvt</input>
				<action>echo urxvt</action>
			</button>
			<button>
				<input type="icon">sylpheed</input>
				<action>echo sylpheed</action>
			</button>
			<button>
				<input type="icon">so</input>
				<action>echo so</action>
			</button>
			<button>
				<input type="icon">scribus</input>
				<action>echo scribus</action>
			</button>
			<button>
				<input type="icon">rxvt</input>
				<action>echo rxvt</action>
			</button>
			<button>
				<input type="icon">paste</input>
				<action>echo paste</action>
			</button>
			<button>
				<input type="icon">package</input>
				<action>echo package</action>
			</button>
			<button>
				<input type="icon">outbox</input>
				<action>echo outbox</action>
			</button>
		</hbox>
		<hbox>
			<button>
				<input type="icon">network</input>
				<action>echo network</action>
			</button>
			<button>
				<input type="icon">inkscape</input>
				<action>echo inkscape</action>
			</button>
			<button>
				<input type="icon">inbox</input>
				<action>echo inbox</action>
			</button>
			<button>
				<input type="icon">icewm-logo</input>
				<action>echo icewm-logo</action>
			</button>
			<button>
				<input type="icon">icewin</input>
				<action>echo icewin</action>
			</button>
			<button>
				<input type="icon">html</input>
				<action>echo html</action>
			</button>
			<button>
				<input type="icon">gz</input>
				<action>echo gz</action>
			</button>
			<button>
				<input type="icon">gtktheme</input>
				<action>echo gtktheme</action>
			</button>
			<button>
				<input type="icon">gtkhash</input>
				<action>echo gtkhash</action>
			</button>
			<button>
				<input type="icon">grubconfig</input>
				<action>echo grubconfig</action>
			</button>
		</hbox>
		<hbox>
			<button>
				<input type="icon">gparted</input>
				<action>echo gparted</action>
			</button>
			<button>
				<input type="icon">gnome-mplayer</input>
				<action>echo gnome-mplayer</action>
			</button>
			<button>
				<input type="icon">top</input>
				<action>echo top</action>
			</button>
			<button>
				<input type="icon">midori</input>
				<action>echo midori</action>
			</button>
			<button>
				<input type="icon">extension</input>
				<action>echo extension</action>
			</button>
			<button>
				<input type="icon">news-feed</input>
				<action>echo news-feed</action>
			</button>
			<button>
				<input type="icon">gexec</input>
				<action>echo gexec</action>
			</button>
			<button>
				<input type="icon">geany</input>
				<action>echo geany</action>
			</button>
			<button>
				<input type="icon">adblock</input>
				<action>echo adblock</action>
			</button>
			<button>
				<input type="icon">abiword</input>
				<action>echo abiword</action>
			</button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
