#!/bin/sh

GTKDIALOG=gtkdialog3

MAIN_DIALOG='
<window title="Example Window" icon-name="gtk-dialog-warning">
	<vbox>
		<frame Description>
			<text>
				<label>Close via the title bar</label>
			</text>
		</frame>
		<hbox>
			<button stock="ok"/>
			<button stock="cancel"/>
		</hbox>
	</vbox>
	<action signal="delete-event">echo delete-event</action>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
