#!/bin/sh

GTKDIALOG=gtkdialog3

MAIN_DIALOG='
<window>
	<vbox>
		<frame Description>
			<text>
				<label>This is an example window.</label>
			</text>
		</frame>
		<hbox>
			<button stock="ok"/>
			<button stock="cancel"/>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
