#!/bin/sh

GTKDIALOG=gtkdialog3

MAIN_DIALOG="
<window title='System Configuration' resizable='false'>
	<vbox spacing='6' border-width='8'>
		<frame title='Description'>
			<text>
				<label>Please enter a hostname for this machine. The hostname
is used to identify the computer on the network and
should contain only lowercase letters, digits, and
hyphens. It must not start or end with a hyphen.

Examples: workstation, dev-server, laptop-home</label>
			</text>
		</frame>
		<frame title='Hostname'>
			<entry>
				<default>localhost</default>
				<variable>entHostname</variable>
			</entry>
		</frame>
		<buttonbox layout='end'>
			<button stock='cancel'/>
			<button stock='ok'/>
		</buttonbox>
	</vbox>
</window>
"
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
