#!/bin/sh

GTKDIALOG=gtkdialog3

MAIN_DIALOG="
<window title='Confirm Action' resizable='false'>
	<vbox spacing='6' border-width='8'>
		<frame title='Question'>
			<text>
				<label>You are about to permanently remove the selected packages
and their configuration files from the system.
This operation cannot be undone.

Any data stored by these packages will also be deleted,
including databases, log files, and cached content.

Do you want to continue?</label>
			</text>
		</frame>
		<buttonbox layout='end'>
			<button stock='no'/>
			<button stock='yes'/>
		</buttonbox>
	</vbox>
</window>
"
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
