#!/bin/sh

GTKDIALOG=gtkdialog3

MAIN_DIALOG='
<window>
	<vbox>
		<frame title="Frame1">
			<text><label>Label1</label></text>
			<entry></entry>
		</frame>
		<frame title="Frame2">
			<hbox>
				<text><label>Label2</label></text>
				<entry></entry>
			</hbox>
		</frame>
		<hbox>
			<button stock="cancel"/>
			<button stock="help"/>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
