#!/bin/sh

# Thunor: The FILE_BROWSE_NEWDIRECTORY example crashes if a directory
# name isn't supplied.

GTKDIALOG=gtkdialog3

MAIN_DIALOG='
<window>
	<vbox>
		<frame title="Simple">
			<hbox>
				<entry>
					<variable>FILE</variable>
				</entry>
				<button>
					<input file stock="gtk-open"></input>
					<variable>FILE_BROWSE</variable>
					<action function="fileselect">FILE</action>
				</button>
			</hbox>
		</frame>
		<frame title="Filename">
			<hbox>
				<entry accept="filename">
					<label>Select an Existing File</label>
					<variable>FILE_FILENAME</variable>
				</entry>
				<button>
					<input file stock="gtk-open"></input>
					<variable>FILE_BROWSE_FILENAME</variable>
					<action function="fileselect">FILE_FILENAME</action>
				</button>
			</hbox>
		</frame>
		<frame title="Filename for Save">
			<hbox>
				<entry accept="savefilename">
					<label>Select a Filename</label>
					<variable>FILE_SAVEFILENAME</variable>
				</entry>
				<button>
					<input file stock="gtk-open"></input>
					<variable>FILE_BROWSE_SAVEFILENAME</variable>
					<action function="fileselect">FILE_SAVEFILENAME</action>
				</button>
			</hbox>
		</frame>
		<frame title="Directory">
			<hbox>
				<entry accept="directory">
					<label>Select a Directory</label>
					<variable>FILE_DIRECTORY</variable>
				</entry>
				<button>
					<input file stock="gtk-open"></input>
					<variable>FILE_BROWSE_DIRECTORY</variable>
					<action function="fileselect">FILE_DIRECTORY</action>
				</button>
			</hbox>
		</frame>
		<frame title="New Directory">
			<hbox>
				<entry accept="newdirectory">
					<label>Create New Directory (really)</label>
					<variable>FILE_NEWDIRECTORY</variable>
				</entry>
				<button>
					<input file stock="gtk-open"></input>
					<variable>FILE_BROWSE_NEWDIRECTORY</variable>
					<action function="fileselect">FILE_NEWDIRECTORY</action>
				</button>
			</hbox>
		</frame>
		<hbox>
			<button stock="ok"/>
			<button stock="cancel"/>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
