#!/bin/sh

GTKDIALOG=gtkdialog3

MAIN_DIALOG='
<window>
	<vbox>
		<edit>
			<variable>EDITOR</variable>
			<height>150</height>
			<width>350</width>
			<default>
"This is the default text of the editor."
			</default>
		</edit>
		<hbox>
			<button stock="cancel"/>
			<button stock="ok"/>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
