#!/bin/sh

GTKDIALOG=gtkdialog3

MAIN_DIALOG="
<window>
	<vbox>
		<hbox>
			<text><label>Label1</label></text>
			<entry/>
		</hbox>
		<hbox>
			<text><label>Label2</label></text>
			<entry/>
		</hbox>
		<hbox>
			<button stock='cancel'/>
			<button stock='help'/>
		</hbox>
	</vbox>
</window>
"
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
