#!/bin/sh

GTKDIALOG=gtkdialog3

IMAGEFILE="`find /usr/share/pixmaps -maxdepth 1 -type f | head -1`"

MAIN_DIALOG='
<window>
	<vbox>
		<hbox>
			<frame title="Pixmap from stock icon_size="1"">
				<pixmap icon_size="1">
					<input type="stock">gtk-save</input>
				</pixmap>
			</frame>
			<frame title="Pixmap from stock icon_size="3"">
				<pixmap icon_size="3">
					<input type="stock">gtk-save</input>
				</pixmap>
			</frame>
		</hbox>
		<hbox>
			<frame title="Pixmap from stock icon_size="5"">
				<pixmap icon_size="5">
					<input type="stock">gtk-save</input>
				</pixmap>
			</frame>
			<frame title="Pixmap from stock icon_size="6"">
				<pixmap icon_size="6">
					<input type="stock">gtk-save</input>
				</pixmap>
			</frame>
		</hbox>
		<hbox>
			<frame title="Pixmap from file">
				<pixmap>
					<input type="file">'"$IMAGEFILE"'</input>
				</pixmap>
			</frame>
			<frame title="Pixmap from file scaled">
				<pixmap>
					<width>128</width>
					<input type="file">'"$IMAGEFILE"'</input>
				</pixmap>
			</frame>
		</hbox>
		<hbox>
			<button stock="cancel"/>
			<button stock="ok"/>
		</hbox>
	</vbox>
</window>
'

export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
